import "server-only";

import {
  createReadStream,
  existsSync,
  mkdirSync,
  statSync,
  unlinkSync,
} from "node:fs";
import { writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

import { dataDir } from "@/lib/auth/secret";
import { db } from "@/lib/db/sqlite";
import { deleteObject, getObject, putObject, toWebStream } from "@/lib/services/s3";
import { sha256Hex } from "@/lib/services/s3-sign";
import {
  DEFAULT_S3_SETTINGS,
  S3SettingsSchema,
  StorageBackend,
  isS3Configured,
  normaliseS3Prefix,
  type S3Settings,
} from "@/types/mits";

/* ──────────────────────────────────────────────────────────────────────────
   Where a blob physically lives.

   One interface, two backends. `lib/storage.ts` above this owns the *rules* —
   who may read what, which extensions are allowed, how a ticket binds its
   attachments — and calls into here for the bytes. Keeping the two apart is what
   made adding S3 a new file rather than an edit to the access checks.

   **The backend is a property of each stored object, not of the instance.** A row
   remembers where it was written; a switch in the settings changes where the
   *next* upload goes and nothing else. Deciding on read from the current setting
   would break every existing attachment the moment somebody switched, and the
   settings page would show a successful save.

   The settings live in `mits_setting` like every other admin-managed value —
   including the secret. Same trade-off as SMTP, documented in AGENTS.md: whoever
   can read the database can already read the sessions.
   ────────────────────────────────────────────────────────────────────────── */

const KEY = "storage_s3";

export function getS3Settings(): S3Settings {
  const row = db
    .prepare("SELECT value FROM mits_setting WHERE key = ?")
    .get(KEY) as { value: string } | undefined;
  if (!row) return DEFAULT_S3_SETTINGS;

  try {
    return S3SettingsSchema.parse(JSON.parse(row.value));
  } catch {
    // A hand-edited or partial row takes the same path as a missing one rather
    // than taking the admin page down with it.
    return DEFAULT_S3_SETTINGS;
  }
}

export function setS3Settings(next: S3Settings): S3Settings {
  const parsed = S3SettingsSchema.parse({
    ...next,
    prefix: normaliseS3Prefix(next.prefix),
  });

  db.prepare(
    `INSERT INTO mits_setting (key, value) VALUES (?, ?)
     ON CONFLICT(key) DO UPDATE SET value = excluded.value`,
  ).run(KEY, JSON.stringify(parsed));

  return parsed;
}

/**
 * Which backend a new upload goes to.
 *
 * Both the flag **and** a complete configuration. A switched-on flag over an empty
 * mask would send every upload into a request that cannot be signed; falling back
 * to disk keeps the instance working and leaves the misconfiguration visible on
 * the settings page rather than in a stack trace at the moment somebody attaches a
 * screenshot to an outage ticket.
 *
 * Read per call rather than cached, so a change in the mask applies to the next
 * upload without a restart.
 */
export function activeBackend(s3Enabled: boolean): StorageBackend {
  return s3Enabled && isS3Configured(getS3Settings()) ? "s3" : "disk";
}

function uploadsDir(): string {
  const dir = join(dataDir(), "uploads");
  mkdirSync(dir, { recursive: true });
  return dir;
}

export interface WrittenObject {
  backend: StorageBackend;
  /** Object key for S3, file name for disk. Never derived from the upload's name. */
  objectKey: string;
  /** Hex SHA-256 of the bytes, for integrity and for spotting duplicates. */
  checksum: string;
  size: number;
}

/**
 * Write bytes and report where they went.
 *
 * `objectKey` is generated by the caller and passed in, because the caller is what
 * knows the allowed extension — deriving a name from the upload is what lets
 * `../../server.js` escape a directory, and that rule lives in one place.
 */
export async function writeObject(
  backend: StorageBackend,
  objectKey: string,
  bytes: Buffer,
  contentType: string,
): Promise<WrittenObject> {
  const checksum = sha256Hex(bytes);

  if (backend === "s3") {
    const settings = getS3Settings();
    const key = `${settings.prefix}${objectKey}`;
    await putObject(settings, key, bytes, contentType);
    return { backend, objectKey: key, checksum, size: bytes.byteLength };
  }

  const target = join(uploadsDir(), objectKey);
  // `wx` — refuse to overwrite. The key is a fresh UUID, so a collision means
  // something is badly wrong and silently replacing somebody's attachment is the
  // worst available response.
  await writeFile(target, bytes, { flag: "wx" });
  return { backend, objectKey, checksum, size: bytes.byteLength };
}

export interface ReadObject {
  stream: () => ReadableStream<Uint8Array> | Promise<ReadableStream<Uint8Array>>;
}

/**
 * Open a stored object, or null when the bytes are gone.
 *
 * Null rather than an exception for a missing object: the row exists, the blob
 * does not, and the caller's answer is a 404 either way. A genuine backend failure
 * — bad credentials, unreachable endpoint — still throws, because that is an
 * operational problem and should not be reported to the user as "file not found".
 */
export async function readObject(
  backend: StorageBackend,
  objectKey: string,
): Promise<ReadObject | null> {
  if (backend === "s3") {
    const object = await getObject(getS3Settings(), objectKey);
    if (!object) return null;
    return { stream: () => object.stream };
  }

  const directory = uploadsDir();
  const path = resolve(join(directory, objectKey));
  // Belt and braces: the key is generated, but a hand-edited database row must not
  // be able to read outside the uploads directory either.
  if (!path.startsWith(resolve(directory))) return null;
  if (!existsSync(path) || !statSync(path).isFile()) return null;

  return { stream: () => toWebStream(createReadStream(path)) };
}

/**
 * Remove the bytes. Best effort by design.
 *
 * A blob that outlives its row costs disk space; a row whose delete was rolled
 * back because the object store was briefly unreachable costs the user their
 * ability to remove an attachment. The row is the record, so the row wins and the
 * orphan is accepted.
 */
export async function removeObject(
  backend: StorageBackend,
  objectKey: string,
): Promise<void> {
  try {
    if (backend === "s3") {
      await deleteObject(getS3Settings(), objectKey);
      return;
    }
    const path = resolve(join(uploadsDir(), objectKey));
    if (path.startsWith(resolve(uploadsDir())) && existsSync(path)) {
      unlinkSync(path);
    }
  } catch {
    /* best effort — see above */
  }
}
